"""catalogo puc y tipo de comprobante por tipo de documento

Revision ID: 2ef9a9818925
Revises: 71ea1353961b
Create Date: 2026-08-13 18:19:33.836291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef9a9818925'
down_revision: Union[str, None] = '71ea1353961b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puc_cuentas',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('clase', sa.String(length=60), nullable=False),
    sa.Column('naturaleza', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index('ix_puc_nombre', 'puc_cuentas', ['nombre'], unique=False)
    op.add_column('empresas', sa.Column('comprobante_factura_recibida', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('comprobante_factura_emitida', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('comprobante_nota_credito', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('comprobante_nota_debito', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('comprobante_nomina', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('comprobante_documento_equivalente', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'comprobante_documento_equivalente')
    op.drop_column('empresas', 'comprobante_nomina')
    op.drop_column('empresas', 'comprobante_nota_debito')
    op.drop_column('empresas', 'comprobante_nota_credito')
    op.drop_column('empresas', 'comprobante_factura_emitida')
    op.drop_column('empresas', 'comprobante_factura_recibida')
    op.drop_index('ix_puc_nombre', table_name='puc_cuentas')
    op.drop_table('puc_cuentas')
    # ### end Alembic commands ###
