"""esquema completo etapas 1-4 partida doble y exportacion

Revision ID: 5e8c6d4846ff
Revises: 
Create Date: 2026-08-12 20:06:39.049477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8c6d4846ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sistema_contable', sa.Enum('siigo_pyme', 'world_office', name='sistemacontable'), nullable=False),
    sa.Column('responsable_iva', sa.Boolean(), nullable=False),
    sa.Column('regimen_simple', sa.Boolean(), nullable=False),
    sa.Column('cuenta_proveedores_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_caja_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_banco_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_iva_descontable_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_retefuente_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_reteica_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_reteiva_id', sa.String(length=36), nullable=True),
    sa.Column('cuenta_inc_id', sa.String(length=36), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_banco_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_banco', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_caja_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_caja', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_inc_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_inc', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_iva_descontable_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_iva', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_proveedores_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_proveedores', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_retefuente_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_retefuente', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_reteica_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_reteica', use_alter=True),
    sa.ForeignKeyConstraint(['cuenta_reteiva_id'], ['cuentas_contables.id'], name='fk_empresa_cuenta_reteiva', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit', name='uq_empresa_nit')
    )
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('entidad', sa.String(length=60), nullable=False),
    sa.Column('entidad_id', sa.String(length=36), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('detalle_json', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_empresa_creado', 'auditoria', ['empresa_id', 'creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_empresa_id'), 'auditoria', ['empresa_id'], unique=False)
    op.create_table('cargas_documentos_dian',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('archivo_excel_nombre', sa.String(length=300), nullable=True),
    sa.Column('archivo_zip_nombre', sa.String(length=300), nullable=True),
    sa.Column('total_filas_excel', sa.Integer(), nullable=False),
    sa.Column('total_archivos_zip', sa.Integer(), nullable=False),
    sa.Column('total_relacionados', sa.Integer(), nullable=False),
    sa.Column('total_pendientes_revision', sa.Integer(), nullable=False),
    sa.Column('total_duplicados', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carga_empresa_creado', 'cargas_documentos_dian', ['empresa_id', 'creado_en'], unique=False)
    op.create_index(op.f('ix_cargas_documentos_dian_empresa_id'), 'cargas_documentos_dian', ['empresa_id'], unique=False)
    op.create_table('centros_costo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_centrocosto_empresa_codigo')
    )
    op.create_index(op.f('ix_centros_costo_empresa_id'), 'centros_costo', ['empresa_id'], unique=False)
    op.create_table('cuentas_contables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_cuenta_empresa_codigo')
    )
    op.create_index('ix_cuenta_empresa_codigo', 'cuentas_contables', ['empresa_id', 'codigo'], unique=False)
    op.create_index(op.f('ix_cuentas_contables_empresa_id'), 'cuentas_contables', ['empresa_id'], unique=False)
    op.create_table('importaciones_historico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=300), nullable=False),
    sa.Column('mapeo_columnas_json', sa.Text(), nullable=False),
    sa.Column('total_registros', sa.Integer(), nullable=False),
    sa.Column('registros_validos', sa.Integer(), nullable=False),
    sa.Column('registros_rechazados', sa.Integer(), nullable=False),
    sa.Column('detalle_rechazos_json', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('importado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importaciones_historico_empresa_id'), 'importaciones_historico', ['empresa_id'], unique=False)
    op.create_table('plantillas_exportacion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sistema_contable', sa.Enum('siigo_pyme', 'world_office', name='sistemacontable'), nullable=False),
    sa.Column('delimitador', sa.String(length=5), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('incluir_encabezado', sa.Boolean(), nullable=False),
    sa.Column('formato_fecha', sa.String(length=20), nullable=False),
    sa.Column('columnas_json', sa.Text(), nullable=False),
    sa.Column('equivalencias_cuentas_json', sa.Text(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_plantilla_empresa_nombre')
    )
    op.create_index(op.f('ix_plantillas_exportacion_empresa_id'), 'plantillas_exportacion', ['empresa_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nit', name='uq_proveedor_empresa_nit')
    )
    op.create_index('ix_proveedor_empresa_nit', 'proveedores', ['empresa_id', 'nit'], unique=False)
    op.create_index(op.f('ix_proveedores_empresa_id'), 'proveedores', ['empresa_id'], unique=False)
    op.create_table('exportaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('plantilla_id', sa.String(length=36), nullable=False),
    sa.Column('sistema_contable', sa.Enum('siigo_pyme', 'world_office', name='sistemacontable'), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.Column('cantidad_registros', sa.Integer(), nullable=False),
    sa.Column('facturas_incluidas_json', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('generada', 'error', name='estadoexportacion'), nullable=False),
    sa.Column('errores_json', sa.Text(), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_exportacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exportacion_empresa_creado', 'exportaciones', ['empresa_id', 'creado_en'], unique=False)
    op.create_index(op.f('ix_exportaciones_empresa_id'), 'exportaciones', ['empresa_id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('carga_id', sa.String(length=36), nullable=True),
    sa.Column('cufe', sa.String(length=120), nullable=True),
    sa.Column('numero_factura', sa.String(length=60), nullable=True),
    sa.Column('prefijo', sa.String(length=20), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_emision', sa.String(length=20), nullable=True),
    sa.Column('nit_emisor', sa.String(length=30), nullable=True),
    sa.Column('nombre_emisor', sa.String(length=200), nullable=True),
    sa.Column('direccion_emisor', sa.String(length=300), nullable=True),
    sa.Column('nit_receptor', sa.String(length=30), nullable=True),
    sa.Column('nombre_receptor', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_gravable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('iva', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('inc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('retenciones_json', sa.Text(), nullable=True),
    sa.Column('otros_impuestos_json', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('forma_pago', sa.String(length=60), nullable=True),
    sa.Column('medio_pago', sa.String(length=60), nullable=True),
    sa.Column('conceptos_json', sa.Text(), nullable=True),
    sa.Column('archivo_xml_path', sa.String(length=500), nullable=True),
    sa.Column('archivo_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('excel_fila_json', sa.Text(), nullable=True),
    sa.Column('fuente_extraccion', sa.Enum('xml', 'pdf_texto', 'pdf_ocr', 'excel_dian', name='fuenteextraccion'), nullable=False),
    sa.Column('confianza_extraccion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('campos_extraidos_json', sa.Text(), nullable=True),
    sa.Column('relacionada_con_excel', sa.Boolean(), nullable=False),
    sa.Column('metodo_relacion', sa.String(length=30), nullable=True),
    sa.Column('motivo_no_relacionada', sa.Text(), nullable=True),
    sa.Column('es_posible_duplicado', sa.Boolean(), nullable=False),
    sa.Column('duplicado_de_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.Enum('pendiente_extraccion', 'extraida', 'pendiente_revision', 'pendiente_clasificacion', 'clasificada', 'lista_para_contabilizar', 'contabilizada', 'exportada', 'error', 'duplicada', name='estadofactura'), nullable=False),
    sa.Column('datos_originales_json', sa.Text(), nullable=True),
    sa.Column('datos_corregidos_json', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas_documentos_dian.id'], ),
    sa.ForeignKeyConstraint(['duplicado_de_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factura_empresa_cufe', 'facturas', ['empresa_id', 'cufe'], unique=False)
    op.create_index('ix_factura_empresa_estado', 'facturas', ['empresa_id', 'estado'], unique=False)
    op.create_index('ix_factura_empresa_numero_nit', 'facturas', ['empresa_id', 'numero_factura', 'nit_emisor'], unique=False)
    op.create_index(op.f('ix_facturas_carga_id'), 'facturas', ['carga_id'], unique=False)
    op.create_index(op.f('ix_facturas_cufe'), 'facturas', ['cufe'], unique=False)
    op.create_index(op.f('ix_facturas_empresa_id'), 'facturas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_facturas_nit_emisor'), 'facturas', ['nit_emisor'], unique=False)
    op.create_index(op.f('ix_facturas_numero_factura'), 'facturas', ['numero_factura'], unique=False)
    op.create_table('historial_contable',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('proveedor_id', sa.String(length=36), nullable=False),
    sa.Column('cuenta_id', sa.String(length=36), nullable=False),
    sa.Column('fecha_documento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('numero_documento', sa.String(length=60), nullable=True),
    sa.Column('tipo_documento', sa.String(length=60), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('origen', sa.Enum('importado', 'manual', 'regla', 'sugerencia_aceptada', name='origendecision'), nullable=False),
    sa.Column('importacion_id', sa.String(length=36), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_contables.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['importacion_id'], ['importaciones_historico.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_contable_cuenta_id'), 'historial_contable', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_historial_contable_empresa_id'), 'historial_contable', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_historial_contable_proveedor_id'), 'historial_contable', ['proveedor_id'], unique=False)
    op.create_index('ix_historial_empresa_proveedor', 'historial_contable', ['empresa_id', 'proveedor_id'], unique=False)
    op.create_table('reglas_contables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('criterio_json', sa.Text(), nullable=False),
    sa.Column('cuenta_id', sa.String(length=36), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_contables.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_contables_empresa_id'), 'reglas_contables', ['empresa_id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('factura_id', sa.String(length=36), nullable=False),
    sa.Column('cuenta_id', sa.String(length=36), nullable=False),
    sa.Column('centro_costo_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('debito', 'credito', name='tipomovimiento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_contables.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimiento_empresa_factura', 'movimientos', ['empresa_id', 'factura_id'], unique=False)
    op.create_index(op.f('ix_movimientos_empresa_id'), 'movimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimientos_factura_id'), 'movimientos', ['factura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_factura_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_empresa_id'), table_name='movimientos')
    op.drop_index('ix_movimiento_empresa_factura', table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_reglas_contables_empresa_id'), table_name='reglas_contables')
    op.drop_table('reglas_contables')
    op.drop_index('ix_historial_empresa_proveedor', table_name='historial_contable')
    op.drop_index(op.f('ix_historial_contable_proveedor_id'), table_name='historial_contable')
    op.drop_index(op.f('ix_historial_contable_empresa_id'), table_name='historial_contable')
    op.drop_index(op.f('ix_historial_contable_cuenta_id'), table_name='historial_contable')
    op.drop_table('historial_contable')
    op.drop_index(op.f('ix_facturas_numero_factura'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_nit_emisor'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_empresa_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_cufe'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_carga_id'), table_name='facturas')
    op.drop_index('ix_factura_empresa_numero_nit', table_name='facturas')
    op.drop_index('ix_factura_empresa_estado', table_name='facturas')
    op.drop_index('ix_factura_empresa_cufe', table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_exportaciones_empresa_id'), table_name='exportaciones')
    op.drop_index('ix_exportacion_empresa_creado', table_name='exportaciones')
    op.drop_table('exportaciones')
    op.drop_index(op.f('ix_proveedores_empresa_id'), table_name='proveedores')
    op.drop_index('ix_proveedor_empresa_nit', table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_plantillas_exportacion_empresa_id'), table_name='plantillas_exportacion')
    op.drop_table('plantillas_exportacion')
    op.drop_index(op.f('ix_importaciones_historico_empresa_id'), table_name='importaciones_historico')
    op.drop_table('importaciones_historico')
    op.drop_index(op.f('ix_cuentas_contables_empresa_id'), table_name='cuentas_contables')
    op.drop_index('ix_cuenta_empresa_codigo', table_name='cuentas_contables')
    op.drop_table('cuentas_contables')
    op.drop_index(op.f('ix_centros_costo_empresa_id'), table_name='centros_costo')
    op.drop_table('centros_costo')
    op.drop_index(op.f('ix_cargas_documentos_dian_empresa_id'), table_name='cargas_documentos_dian')
    op.drop_index('ix_carga_empresa_creado', table_name='cargas_documentos_dian')
    op.drop_table('cargas_documentos_dian')
    op.drop_index(op.f('ix_auditoria_empresa_id'), table_name='auditoria')
    op.drop_index('ix_auditoria_empresa_creado', table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
