"""tipo_comprobante_override en factura para forzar en bloque

Revision ID: a23b3db42855
Revises: f95ac5d354c3
Create Date: 2026-08-18 22:13:48.085241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23b3db42855'
down_revision: Union[str, None] = 'f95ac5d354c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('tipo_comprobante_override', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'tipo_comprobante_override')
    # ### end Alembic commands ###
